### Get index
GET http://localhost:3000/

### Create user
POST http://localhost:3000/user/create
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Login user
# @name loginUser
POST http://localhost:3000/user/login
Content-Type: application/json
{
  "username": "test",
  "password": "test"
}

### Logout user
# @ref loginUser
DELETE http://localhost:3000/user/logout
Cookie: {{loginUserResponse.rawHeaders[3].split(';')[0]}}